### ISSUE TITLE
Question about Code Release and License for Diffblender

### ISSUE THREAD

**Issue by ninjasaid2k** [sungnyun/diffblender#1]
I am writing to inquire about the release of the code for Diffblender. Could you kindly let me know if there are any plans to make the code publicly available, and if so, under what license will it be released?

Thank you for your time and consideration.

**Comment by sungnyun** [comment]
Hi @ninjasaid2k,

Thank you for your interest in our work. I'm excited to announce that the code and model checkpoint will soon be released, although there is a slight delay with some internal reviews. Hopefully, it will be available no later than June. Stay tuned for further updates. 😃
